POST http://localhost:3004/api/v1/marvel/game
Content-Type: application/json

{
  "hands": {
    "p1": [
      {
        "id": 1011147,
        "name": "Korath",
        "description": "",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/8/a0/4c002f7453eaa.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011147",
        "wiki": "http://marvel.com/universe/Korath?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Korath",
        "attacks": [
          22,
          [
            4,
            6,
            5,
            7
          ]
        ],
        "values": {
          "top": 4,
          "right": 6,
          "bottom": 5,
          "left": 7
        }
      },
      {
        "id": 1014666,
        "name": "Red Guardian (Alexei Shostakov)",
        "description": "",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1014666",
        "wiki": "http://marvel.com/universe/Red%20Guardian%20(Alexei%20Shostakov)?utm_campaign=apiRef&utm_source=ddeb243d00b501a84330fefd016bfa92",
        "urlCharacters": "http://marvel.com/characters/Red-Guardian-Alexei-Shostakov",
        "attacks": [
          19,
          [
            5,
            6,
            5,
            3
          ]
        ],
        "values": {
          "top": 5,
          "right": 6,
          "bottom": 5,
          "left": 3
        }
      },
      {
        "id": 1010975,
        "name": "Shadowcat (Age of Apocalypse)",
        "description": "Katherine Pryde lived in the suburbs of Illinois and kept her mutant abilities a secret.",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/f/80/535feaf1a92ef.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1010975",
        "wiki": "http://marvel.com/universe/Shadowcat_%28Age_of_Apocalypse%29?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Shadowcat-Age-of-Apocalypse",
        "attacks": [
          19,
          [
            3,
            4,
            3,
            9
          ]
        ],
        "values": {
          "top": 3,
          "right": 4,
          "bottom": 3,
          "left": 9
        }
      },
      {
        "id": 1011232,
        "name": "Supernaut",
        "description": "Sergeant Milo Fields was recruited for the Order and regained the use of his legs after his nervous system intermingled with that of Aralune.",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/5/90/4c002f048e0b6.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011232",
        "wiki": "http://marvel.com/universe/Supernaut?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Supernaut",
        "attacks": [
          18,
          [
            3,
            4,
            6,
            5
          ]
        ],
        "values": {
          "top": 3,
          "right": 4,
          "bottom": 6,
          "left": 5
        }
      },
      {
        "id": 1010946,
        "name": "Jean Grey (Ultimate)",
        "description": "",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/f/b0/53176f424c100.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1010946",
        "wiki": "http://marvel.com/universe/Marvel_Girl_(Ultimate)?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Marvel-Girl-Ultimate",
        "attacks": [
          17,
          [
            6,
            2,
            5,
            4
          ]
        ],
        "values": {
          "top": 6,
          "right": 2,
          "bottom": 5,
          "left": 4
        }
      }
    ],
    "p2": [
      {
        "id": 1011249,
        "name": "Red 9",
        "description": "",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011249",
        "wiki": "http://marvel.com/universe/Red%209?utm_campaign=apiRef&utm_source=ddeb243d00b501a84330fefd016bfa92",
        "urlCharacters": "http://marvel.com/characters/Red-9",
        "attacks": [
          16,
          [
            2,
            5,
            7,
            2
          ]
        ],
        "values": {
          "top": 2,
          "right": 5,
          "bottom": 7,
          "left": 2
        }
      },
      {
        "id": 1010937,
        "name": "Josiah X",
        "description": "",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1010937",
        "wiki": "http://marvel.com/universe/Josiah_X?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Josiah-X",
        "attacks": [
          23,
          [
            3,
            8,
            9,
            3
          ]
        ],
        "values": {
          "top": 3,
          "right": 8,
          "bottom": 9,
          "left": 3
        }
      },
      {
        "id": 1017834,
        "name": "War Machine (James Rhodes)",
        "description": "<span style=\"color: #333333; font-family: &amp;amp;amp; font-size: 14.4px; letter-spacing: normal; line-height: normal; background-color: #eeeeee;\">U.S. Air Force pilot and Tony Stark's friend who has his own suit of Iron Man armor, nicknamed, \"War Machine.\"</span>",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1017834",
        "wiki": "http://marvel.com/universe/War%20Machine%20(James%20Rhodes)?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/War-Machine-James-Rhodes",
        "attacks": [
          18,
          [
            5,
            3,
            5,
            5
          ]
        ],
        "values": {
          "top": 5,
          "right": 3,
          "bottom": 5,
          "left": 5
        }
      },
      {
        "id": 1010872,
        "name": "Vector",
        "description": "Simon Utrecht wanted superhuman powers in order to persue personal power and gain, and commissioned a project that would ultimately simulate the crash that gave the Fantastic Four their powers; he has remained with the U-Foes ever since.",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/8/80/4c0035a7dd04d.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1010872",
        "wiki": "http://marvel.com/universe/Vector?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Vector",
        "attacks": [
          20,
          [
            3,
            6,
            5,
            6
          ]
        ],
        "values": {
          "top": 3,
          "right": 6,
          "bottom": 5,
          "left": 6
        }
      },
      {
        "id": 1011367,
        "name": "Dark Avengers",
        "description": "",
        "thumbnail": {
          "path": "http://i.annihil.us/u/prod/marvel/i/mg/f/a0/526032c703d06.jpg"
        },
        "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011367",
        "wiki": "http://marvel.com/universe/Dark%20Avengers?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
        "urlCharacters": "http://marvel.com/characters/Dark-Avengers",
        "attacks": [
          15,
          [
            4,
            4,
            3,
            4
          ]
        ],
        "values": {
          "top": 4,
          "right": 4,
          "bottom": 3,
          "left": 4
        }
      }
    ]
  },
  "currentPlayer": "p1",
  "board": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "move": {
    "id": 1011147,
    "hits": [
      4,
      6,
      5,
      7
    ],
    "position": 1
  }
}

###
POST http://localhost:3004/api/v1/marvel/game/start
Content-Type: application/json

{
  "characters": [
    {
      "id": 1011147,
      "name": "Korath",
      "description": "",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/8/a0/4c002f7453eaa.jpg"
      },
      "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011147",
      "wiki": "http://marvel.com/universe/Korath?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
      "urlCharacters": "http://marvel.com/characters/Korath",
      "attacks": [
        22,
        [
          4,
          6,
          5,
          7
        ]
      ],
      "values": {
        "top": 4,
        "right": 6,
        "bottom": 5,
        "left": 7
      }
    },
    {
      "id": 1014666,
      "name": "Red Guardian (Alexei Shostakov)",
      "description": "",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg"
      },
      "resourceURI": "http://gateway.marvel.com/v1/public/characters/1014666",
      "wiki": "http://marvel.com/universe/Red%20Guardian%20(Alexei%20Shostakov)?utm_campaign=apiRef&utm_source=ddeb243d00b501a84330fefd016bfa92",
      "urlCharacters": "http://marvel.com/characters/Red-Guardian-Alexei-Shostakov",
      "attacks": [
        19,
        [
          5,
          6,
          5,
          3
        ]
      ],
      "values": {
        "top": 5,
        "right": 6,
        "bottom": 5,
        "left": 3
      }
    },
    {
      "id": 1010975,
      "name": "Shadowcat (Age of Apocalypse)",
      "description": "Katherine Pryde lived in the suburbs of Illinois and kept her mutant abilities a secret.",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/f/80/535feaf1a92ef.jpg"
      },
      "resourceURI": "http://gateway.marvel.com/v1/public/characters/1010975",
      "wiki": "http://marvel.com/universe/Shadowcat_%28Age_of_Apocalypse%29?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
      "urlCharacters": "http://marvel.com/characters/Shadowcat-Age-of-Apocalypse",
      "attacks": [
        19,
        [
          3,
          4,
          3,
          9
        ]
      ],
      "values": {
        "top": 3,
        "right": 4,
        "bottom": 3,
        "left": 9
      }
    },
    {
      "id": 1011232,
      "name": "Supernaut",
      "description": "Sergeant Milo Fields was recruited for the Order and regained the use of his legs after his nervous system intermingled with that of Aralune.",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/5/90/4c002f048e0b6.jpg"
      },
      "resourceURI": "http://gateway.marvel.com/v1/public/characters/1011232",
      "wiki": "http://marvel.com/universe/Supernaut?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
      "urlCharacters": "http://marvel.com/characters/Supernaut",
      "attacks": [
        18,
        [
          3,
          4,
          6,
          5
        ]
      ],
      "values": {
        "top": 3,
        "right": 4,
        "bottom": 6,
        "left": 5
      }
    },
    {
      "id": 1010946,
      "name": "Jean Grey (Ultimate)",
      "description": "",
      "thumbnail": {
        "path": "http://i.annihil.us/u/prod/marvel/i/mg/f/b0/53176f424c100.jpg"
      },
      "resourceURI": "http://gateway.marvel.com/v1/public/characters/1010946",
      "wiki": "http://marvel.com/universe/Marvel_Girl_(Ultimate)?utm_campaign=apiRef&utm_source=d0522038ca5d2d32ec335cc0e418e27c",
      "urlCharacters": "http://marvel.com/characters/Marvel-Girl-Ultimate",
      "attacks": [
        17,
        [
          6,
          2,
          5,
          4
        ]
      ],
      "values": {
        "top": 6,
        "right": 2,
        "bottom": 5,
        "left": 4
      }
    }
  ]
}

###
GET http://localhost:3004/api/v1/marvel/create
Accept: application/json

###
