GET http://localhost:4444/
###
POST http://localhost:4444/auth/login
content-type: application/json

{
    "email" : "test1@test.ru",
    "password" : "test1"
}
###
POST http://localhost:4444/auth/register
content-type: application/json

{
    "email" : "test1@test.ru",
    "password" : "test1",
    "fullName": "Vasya Pupkin",
    "avatarUrl" : "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/0e/0eabb3ba0f9f3c6ff1602d7ff6b00723e56329e0.jpg"
}

###
GET http://localhost:4444/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmYxN2FiM2U0Y2QzZjQ3OGNhNjIxMjciLCJpYXQiOjE2NTk5OTUwMzMsImV4cCI6MTY2MjU4NzAzM30.T8BgL3nu-pQ5S-EaObGy3XqFBB7e8Ml0tB6uFVIvH-g

###
POST http://localhost:4444/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmYxN2FiM2U0Y2QzZjQ3OGNhNjIxMjciLCJpYXQiOjE2NjAxNjkxOTQsImV4cCI6MTY2Mjc2MTE5NH0.zkAUpAvwuQZzi0ABrESraNHQK6RljsM_2rgv3d-G-vo

{
    "title" : "My first post",
    "text" : "This is my first text. Let's go mf !!! :D",
    "imageUrl" : "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/0e/0eabb3ba0f9f3c6ff1602d7ff6b00723e56329e0.jpg",
    "tags": ["story","nevergiveup", "first one"]
}