###
POST http://localhost:8080/api/v1/auth/register
content-type: application/json

{
    "email" : "test@test.ru",
    "password" : "test1",
    "name": "Albert",
    "avatarUrl" : "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/0e/0eabb3ba0f9f3c6ff1602d7ff6b00723e56329e0.jpg"

}