#Get all records
GET http://localhost:8080/api/v1/records

###
#Get one record by ID
GET http://localhost:8080/api/v1/records/0bff586f-2017-4526-9e52-fe3ea46d55ab

###
#Get records for workout ID
GET http://localhost:8080/api/v1/workouts/4a3d9aaa-608c-49a7-a004-66305ad4ab50/records

###
# Create new record
POST http://localhost:8080/api/v1/records
content-type: application/json

{
  "workout": "d8be2362-7b68-4ea4-a1f6-03f8bc4eede7",
  "record": "5:23 minutes"
}

###
# Delete record
DELETE  http://localhost:8080/api/v1/records/62251cfe-fdb6-4fa6-9a2d-c21be93ac78d
