#Get all workouts
GET http://localhost:8080/api/v1/workouts

###

#Get random workout
GET http://localhost:8080/api/v1/workouts/random

###
#Get one workout by ID
GET http://localhost:8080/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6

###
#Get records for Workout
GET http://localhost:8080/api/v1/workouts/4a3d9aaa-608c-49a7-a004-66305ad4ab50/records

###
#Get workouts using querry params

# ?length=
GET http://localhost:8080/api/v1/workouts?length=3
###

# ?page=
GET http://localhost:8080/api/v1/workouts?page=2
###

# ?mode=
GET http://localhost:8080/api/v1/workouts?mode=amrap
###

# ?equipment=
GET http://localhost:8080/api/v1/workouts?equipment=dumbbell
###
GET http://localhost:8080/api/v1/workouts?equipment=row%20erg
###


# Create new workout
POST http://localhost:8080/api/v1/workouts
content-type: application/json

{
  "name": "Jump & Push 3",
  "mode": "AMRAP",
  "timer": "reb",
  "time": 900,
  "exercises": [
   "15 Air squats",
   "10 Push-ups",
   "66"
  ]
 
}
###
# Update workout
PATCH   http://localhost:8080/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6
content-type: application/json

{
  "name": "PATCH Tommy V",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ]
}
###
# Delete workout
DELETE  http://localhost:8080/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6
